# -*- coding: utf-8 -*-
"""cropphotos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15WjnL8t747nlvam5gRcsrWY1-Sv67Q-t
"""

# Load the Drive helper and mount
from google.colab import drive
import os
import json

# This will prompt for authorization.
drive.mount('/content/gdrive')

import tempfile
def download_and_resize_image(url, new_width=256, new_height=256,
                              display=False):
  _, filename = tempfile.mkstemp(suffix=".jpg")
  pil_image = Image.open(url)
  pil_image = ImageOps.fit(pil_image, (new_width, new_height), Image.ANTIALIAS)
  pil_image_rgb = pil_image.convert("RGB")
  pil_image_rgb.save(filename, format="JPEG", quality=90)
  print("Image downloaded to %s." % filename)
  if display:
    display_image(pil_image)
  return filename

base_metaData_directory = "/content/gdrive/My Drive/Capstone 2019/ImageMetaData/"
# with open(base_metaData_directory, "r") as read_file:
#   test = json.load(read_file)

print(test['images'])

imageMetaData = {}
for i in os.listdir(base_metaData_directory):
  with open(base_metaData_directory + i, "r") as read_file:
    imageMetaData[i] = json.load(read_file)

print(imageMetaData['n02274822_2.JSON'])
print(imageMetaData['n02274822_2.JSON']['images']['left'])

import numpy as np
from PIL import Image
from PIL import ImageColor
from PIL import ImageDraw
from PIL import ImageFont
from PIL import ImageOps
# os and glob
import glob
import os
import tarfile
import cv2
import scipy.misc
import json

def crop_photos(image,filename, outgoingpath):
  pil_image = Image.open(image)
  if filename in imageMetaData:
    jsonfile = imageMetaData[filename]
    data = jsonfile['images']
    d = pil_image.crop((data['left'], data['top'] , data['right'] , data['bottom']))
    d.save(outgoingpath)
  else:
    print("does not exist")

import matplotlib.pyplot as plt
def display_image(image):
  fig = plt.figure(figsize=(20, 15))
  plt.grid(False)
  plt.imshow(image)
downloaded_image_path = download_and_resize_image("/content/gdrive/My Drive/Capstone 2019/ImageDataset/cabbage/objdetphotos/n02280649_12.JPEG" , 640, 480)
crop_photos(downloaded_image_path ,'n02280649_12.JSON' ,"/content/gdrive/My Drive/Capstone 2019/ImageDataset/cabbage/croppedphotos/n02280649_12.JPEG")

base_clean_directory = "/content/gdrive/My Drive/Capstone 2019/ImageDataset/"
for dir in glob.glob( os.path.join(base_clean_directory,  '*') ):
  if os.path.isdir(dir):
    for filename in os.listdir(dir + "/cleanphotos"):

      imgtocrop = download_and_resize_image( dir + "/cleanphotos/" + filename, 640, 480)
      jfile = filename[0: len(filename) - 4] + "JSON"
      #print(filename)
      #print(jfile)
      crop_photos(imgtocrop, jfile , dir + "/croppedphotos/" + filename )